#!/bin/bash
# Make a gnirehtet release.
#
# Put your keystore properties into ~/.gradle/gradle.properties
# (check app/build.gradle)

set -e # fail on error

GRADLE=${GRADLE:-./gradlew} # set value ./gradlew if not set
DIST=dist
TARGET_DIR_JAVA=gnirehtet-java

version=$(git describe --tags --always)
TARGET_JAVA="$TARGET_DIR_JAVA-$version".zip

./relay-java/gradlew -p relay-java assembleRelease

rm -rf "$DIST"

mkdir -p "$DIST/$TARGET_DIR_JAVA"
cp gnirehtet.apk "$DIST/$TARGET_DIR_JAVA"/gnirehtet.apk

cp relay-java/build/libs/gnirehtet.jar \
   gnirehtet_watchdog.py \
   run_watchdog.cmd \
   run_watchdog.sh \
   NOTICE \
   LICENSE \
   "$DIST/$TARGET_DIR_JAVA"/

cd "$DIST"
zip -r "$TARGET_JAVA" "$TARGET_DIR_JAVA"
sha256sum "$TARGET_JAVA" > SHA256SUMS.txt

