apply plugin: 'checkstyle'

checkstyle {
    toolVersion = '10.12.5'
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml").exists() ?
                 file("${project.rootDir}/config/checkstyle/checkstyle.xml") :
                 file("${project.rootDir}/../config/checkstyle/checkstyle.xml")
}
